name: phenoscope-build
channels:
  - conda-forge
  - bioconda
  - r
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - matplotlib
  - numpy
  - pandas
  - scikit-image
  - scikit-learn
  - opencv
  - jupyter
  - dash
  - joblib
  - docutils
  - h5py
  - imageio
  - mahotas
  - inflect
  - mysqlclient=1.4.6
  - psutil
  - pytest
  - scipy
  - scyjava
  - seaborn
  - pip
  - bioconda::centrosome
  - pip:
    - python-javabridge
    - CellProfiler
    - cellprofiler-core
  # Other dependencies:
  #   Jave Runtime Environment or Java Development Kit
  #   MySQL package config (https://github.com/PyMySQL/mysqlclient)
