name: phenoscope-build
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - python=3.12
  - absl-py
  - matplotlib
  - numpy
  - pandas
  - scikit-image
  - scikit-learn
  - dash
  - joblib
  - boto3
  - docutils
  - h5py
  - imageio
  - mahotas
  - psutil
  - pytest
  - pyzmq
  - scipy
  - scyjava
  - seaborn
  - jupyter
  - pip:
      - sphinx
      - sphinxcontrib-napoleon
      - sphinx-autodoc-typehints
      - sphinxawesome-theme
      - furo
      - pydata-sphinx-theme

#    - python-javabridge
#    - centrosome
#    - cellprofiler
#    - cellprofiler-core
  # Other dependencies:
  #   Jave Runtime Environment or Java Development Kit
  #   MySQL package config (https://github.com/PyMySQL/mysqlclient)
