name: phenoscope-build
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.10
  - matplotlib
  - numpy
  - pandas
  - scikit-image
  - scikit-learn
  - opencv
  - jupyter
  - dash
  - joblib
  - boto3
  - docutils
  - h5py
  - imageio
  - mahotas
  - psutil
  - pytest
  - scipy
  - scyjava
  - seaborn
  - bioconda::centrosome
  - bioconda::cellprofiler
  - bioconda::cellprofiler-core
  # Other dependencies:
  #   Jave Runtime Environment or Java Development Kit
