name: PhenoTypic
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.12
  - absl-py
  - matplotlib
  - numpy
  - pandas
  - scikit-image
  - scikit-learn
  - dash
  - joblib
  - boto3
  - docutils
  - h5py
  - imageio
  - mahotas
  - psutil
  - pytest
  - pyzmq
  - scipy
  - scyjava
  - seaborn
#  - python-javabridge
#  - bioconda::centrosome
#  - bioconda::cellprofiler_api=4.2.6
#  - bioconda::cellprofiler_api-core=4.2.6
  # Other dependencies:
  #   Jave Runtime Environment or Java Development Kit
